import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";

import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import { GlobalContextProvider, initialContextValue } from "@/contexts";
import Navbar from "@/components/common/Navbar/Navbar";
import { headers } from "next/headers";

const inter = Inter({ subsets: ["latin"] });
const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const getIsSsrMobile = (context: GetServerSidePropsContext) => {
  //  return  /iPhone|iPad|iPod|Android/i.test(context.req.headers["user-agent"] as string);

  // };
  const headersInstance = headers();
  const userAgent = headersInstance?.get("user-agent");
  const isMobileDevice = (): boolean =>
    /iPhone|iPad|iPod|Android/i.test(userAgent || "");

  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;600;700&display=swap"
        />
      </head>
      {!isMobileDevice() ? (
        <div className="h-screen w-screen flex justify-center items-center font-bold text-2xl px-2">
          Nous ne sommes disponibles que sur SmartPhone!
        </div>
      ) : (
        <GlobalContextProvider {...initialContextValue}>
          <body className={montserrat.className}>
            <Navbar></Navbar>
            {children}
          </body>
        </GlobalContextProvider>
      )}
    </html>
  );
}
